export STREAMS_CLIENT_JMXCONNECT=service:jmx:jmxmp://localhost:9975
export STREAMS_CLIENT_USERNAME=streamsadmin
export STREAMS_CLIENT_PASSWORD=passw0rd
export STREAMS_CLIENT_JMX_SSLOPTION=TLSv1.2
export STREAMS_DOMAIN_ID=StreamsDomain
export STREAMS_INSTANCE_ID=StreamsInstance
export STREAMS_CLIENT_JMX_HTTP_HOST=localhost
